// =================================================================
// ██████╗██╗  ██╗ █████╗ ████████╗███████╗██████╗  █████╗ 
// ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗
// ██║     ███████║███████║   ██║   █████╗  ██████╔╝███████║
// ██║     ██╔══██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║
// ╚██████╗██║  ██║██║  ██║   ██║   ███████╗██║  ██║██║  ██║
//  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
// GENERATED BY CLAUDE: ChatEra v1.0 – 2025-05-13
// =================================================================

/**
 * ████████╗ █████╗ ██╗██╗     ██╗    ██╗██╗███╗   ██╗██████╗      ██████╗███████╗███████╗
 * ╚══██╔══╝██╔══██╗██║██║     ██║    ██║██║████╗  ██║██╔══██╗    ██╔════╝██╔════╝██╔════╝
 *    ██║   ███████║██║██║     ██║ █╗ ██║██║██╔██╗ ██║██║  ██║    ██║     ███████╗███████╗
 *    ██║   ██╔══██║██║██║     ██║███╗██║██║██║╚██╗██║██║  ██║    ██║     ╚════██║╚════██║
 *    ██║   ██║  ██║██║███████╗╚███╔███╔╝██║██║ ╚████║██████╔╝    ╚██████╗███████║███████║
 *    ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝ ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝      ╚═════╝╚══════╝╚══════╝
 * 
 * [CODEX] Tailwind CSS Configuration
 * 
 * This file configures Tailwind CSS for the ChatEra application.
 * It defines custom colors, extensions, and theme settings to achieve
 * a nostalgic MSN Messenger-inspired UI with modern sensibilities.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // MSN Messenger inspired color palette with modern touch
        msn: {
          blue: "#2D8CFF",
          green: "#7FBA00",
          orange: "#FF8C00",
          red: "#F25022",
          purple: "#9333EA",
          yellow: "#FFB900",
          gray: {
            50: "#F9FAFB",
            100: "#F3F4F6",
            200: "#E5E7EB",
            300: "#D1D5DB",
            400: "#9CA3AF",
            500: "#6B7280",
            600: "#4B5563",
            700: "#374151",
            800: "#1F2937",
            900: "#111827",
            950: "#030712",
          },
        },
        // Default Tailwind border radius
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'msn': '0 1px 2px rgba(0, 0, 0, 0.1), 0 2px 6px rgba(45, 140, 255, 0.2)',
        'msn-hover': '0 2px 4px rgba(0, 0, 0, 0.1), 0 4px 12px rgba(45, 140, 255, 0.3)',
        'msn-active': '0 1px 1px rgba(0, 0, 0, 0.05), 0 1px 4px rgba(45, 140, 255, 0.2)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "bounce-light": {
          "0%, 100%": { 
            transform: "translateY(-5%)",
            animationTimingFunction: "cubic-bezier(0.8, 0, 1, 1)" 
          },
          "50%": { 
            transform: "translateY(0)",
            animationTimingFunction: "cubic-bezier(0, 0, 0.2, 1)" 
          },
        },
        "status-pulse": {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.6 },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(100%)" },
        },
        "typing": {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bounce-light": "bounce-light 1s infinite",
        "status-pulse": "status-pulse 2s infinite",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-in",
        "typing": "typing 1.5s steps(20, end)",
      },
      backgroundImage: {
        'msn-gradient': 'linear-gradient(to bottom, #2D8CFF, #2B7FE8)',
        'msn-gradient-hover': 'linear-gradient(to bottom, #3E97FF, #3C8BF4)',
        'msn-noise': "url('/images/noise.png')",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
};
