// =================================================================
// ██████╗██╗  ██╗ █████╗ ████████╗███████╗██████╗  █████╗ 
// ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗
// ██║     ███████║███████║   ██║   █████╗  ██████╔╝███████║
// ██║     ██╔══██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║
// ╚██████╗██║  ██║██║  ██║   ██║   ███████╗██║  ██║██║  ██║
//  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
// GENERATED BY CLAUDE: ChatEra v1.0 – 2025-05-13
// =================================================================

/**
 * ▄▀█ █▀█ █▀█ █▀▀ ▄▀█ █▀█ ▄▀█ █▄░█ █▀▀ █▀▀   █▀█ ▄▀█ █▀▀ █▀▀
 * █▀█ █▀▀ █▀▀ ██▄ █▀█ █▀▄ █▀█ █░▀█ █▄▄ ██▄   █▀▀ █▀█ █▄█ ██▄
 * 
 * [CODEX] Appearance Settings Page
 * 
 * This page allows users to customize the visual appearance of ChatEra,
 * including themes, colors, fonts, and layout options.
 * 
 * Features:
 * - Theme selection (light/dark/system/custom)
 * - Font size and family configuration
 * - Layout density options
 * - Color scheme customization
 * - MSN-inspired visual options
 * - Cross-platform support (Windows/Linux)
 */

import React, { useState } from 'react';
import Head from 'next/head';
import SettingsLayout from '@/components/settings/SettingsLayout';
import AppearanceSettings from '@/components/settings/AppearanceSettings';
import ProtectedRoute from '@/components/auth/ProtectedRoute';

/**
 * [H4X] APPEARANCE SETTINGS PAGE
 * 
 * Page container for appearance settings management
 */
const AppearanceSettingsPage: React.FC = () => {
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  /**
   * [H4X] SAVE CHANGES HANDLER
   * 
   * Callback function to handle saving changes from child components
   */
  const handleSaveChanges = async () => {
    setIsSaving(true);
    
    try {
      // This would normally be the place to aggregate all settings changes
      // and submit them to the API, but since the actual changes happen
      // within the component, we're just simulating the save here
      await new Promise(resolve => setTimeout(resolve, 1000));
      setHasUnsavedChanges(false);
    } catch (error) {
      console.error('Error saving appearance settings:', error);
    } finally {
      setIsSaving(false);
    }
  };
  
  /**
   * [H4X] CANCEL CHANGES HANDLER
   * 
   * Resets all unsaved changes
   */
  const handleCancelChanges = () => {
    setHasUnsavedChanges(false);
    // The actual reset happens in the child component
  };
  
  /**
   * [H4X] TRACK UNSAVED CHANGES
   * 
   * Callback function to track changes from child components
   */
  const trackChanges = (hasChanges: boolean) => {
    setHasUnsavedChanges(hasChanges);
  };
  
  return (
    <ProtectedRoute>
      <Head>
        <title>Appearance Settings | ChatEra</title>
        <meta name="description" content="Customize the visual appearance of your ChatEra application" />
      </Head>
      
      <SettingsLayout
        title="Appearance Settings"
        hasUnsavedChanges={hasUnsavedChanges}
        onSave={handleSaveChanges}
        onCancel={handleCancelChanges}
        currentSection="appearance"
      >
        <AppearanceSettings onSaveChanges={trackChanges} />
      </SettingsLayout>
    </ProtectedRoute>
  );
};

export default AppearanceSettingsPage;
