// =================================================================
// ██████╗██╗  ██╗ █████╗ ████████╗███████╗██████╗  █████╗ 
// ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗
// ██║     ███████║███████║   ██║   █████╗  ██████╔╝███████║
// ██║     ██╔══██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║
// ╚██████╗██║  ██║██║  ██║   ██║   ███████╗██║  ██║██║  ██║
//  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
// GENERATED BY CLAUDE: ChatEra v1.0 – 2025-05-13
// =================================================================

/**
 * █░█░█ █▀▀ █░░ █▀▀ █▀█ █▀▄▀█ █▀▀   █▀ ▀█▀ █▀▀ █▀█
 * ▀▄▀▄▀ ██▄ █▄▄ █▄▄ █▄█ █░▀░█ ██▄   ▄█ ░█░ ██▄ █▀▀
 * 
 * [CODEX] Welcome Step Component
 * 
 * First step in the onboarding process that introduces users
 * to ChatEra, explaining its key features and capabilities
 * with a nostalgic MSN-inspired design.
 * 
 * Features:
 * - Introduction to ChatEra
 * - Platform capabilities overview
 * - Animated visual elements
 * - Cross-platform messaging
 */

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { useTauri } from '@/lib/tauri';
import { 
  MessageSquare, 
  Users, 
  Video, 
  Headphones,
  Shield,
  Globe
} from 'lucide-react';

interface WelcomeStepProps {
  onComplete: (data: any) => void;
  onSkip?: () => void;
  isOptional?: boolean;
}

/**
 * [H4X] FEATURE LIST
 * 
 * Key features of ChatEra highlighted during onboarding
 */
const FEATURES = [
  {
    icon: <MessageSquare size={24} />,
    title: 'Real-time Messaging',
    description: 'Instant messaging with friends and groups, including rich media sharing.',
    color: 'text-msn-blue'
  },
  {
    icon: <Users size={24} />,
    title: 'Friend Networks',
    description: 'Build your contact list and organize them into groups.',
    color: 'text-msn-green'
  },
  {
    icon: <Video size={24} />,
    title: 'Video Calls',
    description: 'Face-to-face conversations with high-quality video calls.',
    color: 'text-msn-purple'
  },
  {
    icon: <Headphones size={24} />,
    title: 'Voice Chat',
    description: 'Clear voice communications with friends and groups.',
    color: 'text-msn-orange'
  },
  {
    icon: <Shield size={24} />,
    title: 'Privacy Controls',
    description: 'Control who can contact you and view your information.',
    color: 'text-msn-red'
  },
  {
    icon: <Globe size={24} />,
    title: 'Cross-Platform',
    description: 'Connect from any device - desktop, web, and mobile.',
    color: 'text-msn-blue-dark'
  }
];

/**
 * [H4X] WELCOME COMPONENT
 * 
 * Initial step in the onboarding flow
 */
const WelcomeStep: React.FC<WelcomeStepProps> = ({
  onComplete,
  onSkip,
  isOptional = false
}) => {
  const { isDesktop } = useTauri();
  const [agreed, setAgreed] = useState(false);
  
  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };
  
  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        type: 'spring',
        stiffness: 300,
        damping: 24
      }
    }
  };
  
  // Logo animation variants
  const logoVariants = {
    hidden: { scale: 0.8, opacity: 0 },
    visible: {
      scale: 1,
      opacity: 1,
      transition: {
        type: 'spring',
        stiffness: 300,
        damping: 20,
        delay: 0.2
      }
    }
  };
  
  // Proceed to next step
  const handleContinue = () => {
    onComplete({});
  };
  
  return (
    <div className="h-full flex flex-col">
      {/* Logo and welcome header */}
      <div className="text-center mb-6">
        <motion.div
          className="mx-auto mb-4"
          variants={logoVariants}
          initial="hidden"
          animate="visible"
        >
          <div className="h-20 w-20 bg-gradient-to-r from-msn-blue to-msn-blue-light rounded-full flex items-center justify-center mx-auto">
            <MessageSquare size={40} className="text-white" />
          </div>
        </motion.div>
        
        <h1 className="text-2xl font-bold mb-2 text-msn-blue">Welcome to ChatEra!</h1>
        <p className="text-msn-gray-600 dark:text-msn-gray-400">
          The modern messaging platform with nostalgic vibes
        </p>
      </div>
      
      {/* Feature highlights */}
      <motion.div 
        className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {FEATURES.map((feature, index) => (
          <motion.div
            key={index}
            className="bg-white dark:bg-msn-gray-800 rounded-lg p-4 shadow-sm flex items-start"
            variants={itemVariants}
          >
            <div className={`mr-3 mt-1 ${feature.color}`}>
              {feature.icon}
            </div>
            <div>
              <h3 className="font-semibold mb-1">{feature.title}</h3>
              <p className="text-sm text-msn-gray-600 dark:text-msn-gray-400">
                {feature.description}
              </p>
            </div>
          </motion.div>
        ))}
      </motion.div>
      
      {/* Privacy agreement */}
      <div className="mt-auto pt-4">
        <div className="flex items-start mb-4">
          <input
            id="privacy-agree"
            type="checkbox"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
            className="mt-1 h-4 w-4 rounded border-msn-gray-300 text-msn-blue focus:ring-msn-blue"
          />
          <label htmlFor="privacy-agree" className="ml-2 text-sm text-msn-gray-700 dark:text-msn-gray-300">
            I agree to the <a href="#" className="text-msn-blue hover:underline">Terms of Service</a> and 
            acknowledge that my personal information will be processed according to the 
            <a href="#" className="text-msn-blue hover:underline"> Privacy Policy</a>.
          </label>
        </div>
        
        {/* Continue button (handled by stepper) */}
        <button 
          onClick={handleContinue}
          disabled={!agreed}
          className="hidden"
        >
          Get Started
        </button>
      </div>
      
      {/* MSN-style footer */}
      <div className="text-center text-xs text-msn-gray-500 mt-6">
        <p>ChatEra v1.0 • {isDesktop ? 'Desktop Edition' : 'Web Edition'}</p>
        <p>© 2025 ChatEra Corporation. All rights reserved.</p>
      </div>
    </div>
  );
};

export default WelcomeStep;
