// =================================================================
// ██████╗██╗  ██╗ █████╗ ████████╗███████╗██████╗  █████╗ 
// ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗
// ██║     ███████║███████║   ██║   █████╗  ██████╔╝███████║
// ██║     ██╔══██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║
// ╚██████╗██║  ██║██║  ██║   ██║   ███████╗██║  ██║██║  ██║
//  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
// GENERATED BY CLAUDE: ChatEra v1.0 – 2025-05-13
// =================================================================

/**
 * ▄▀█ █░█ ▀█▀ █░█   █▀▀ ▄▀█ █▀█ █▀▄
 * █▀█ █▄█ ░█░ █▀█   █▄▄ █▀█ █▀▄ █▄▀
 * 
 * [CODEX] Authentication Card Component
 * 
 * This reusable component provides a consistent card layout for all
 * authentication forms with branding elements and animated transitions.
 * 
 * Features:
 * - Consistent branding for all auth forms
 * - Animated transitions and hover effects
 * - Adaptive design for web and desktop
 * - Light/dark mode support
 * - Optional loading state
 */

import React from 'react';
import { motion } from 'framer-motion';
import { useTauri } from '@/lib/tauri';

interface AuthCardProps {
  children: React.ReactNode;
  title: string;
  subtitle: string;
  footer?: React.ReactNode;
  loading?: boolean;
}

/**
 * [H4X] AUTH CARD COMPONENT
 * 
 * Wrapper for authentication forms with consistent styling
 */
const AuthCard: React.FC<AuthCardProps> = ({ 
  children, 
  title, 
  subtitle, 
  footer, 
  loading = false 
}) => {
  const { isDesktop } = useTauri();
  
  // Adjust card size based on platform
  const cardClasses = `
    bg-white dark:bg-msn-gray-800 
    rounded-lg shadow-xl 
    overflow-hidden
    w-full max-w-md
    border border-msn-gray-200 dark:border-msn-gray-700
    ${isDesktop ? 'min-h-[440px]' : 'min-h-[320px]'}
  `;
  
  // Animation variants
  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { 
      opacity: 1, 
      y: 0,
      transition: { 
        duration: 0.4,
        ease: [0.25, 0.1, 0.25, 1.0] 
      }
    }
  };
  
  return (
    <motion.div
      className={cardClasses}
      initial="hidden"
      animate="visible"
      variants={cardVariants}
    >
      {/* Logo and header */}
      <div className="text-center pt-8 pb-4 px-6">
        {/* Logo */}
        <div className="flex justify-center mb-4">
          <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-msn-blue to-msn-purple flex items-center justify-center">
            <img 
              src="/logo.png" 
              alt="ChatEra" 
              className="w-12 h-12" 
            />
          </div>
        </div>
        
        {/* Title */}
        <h1 className="text-2xl font-bold text-msn-gray-900 dark:text-white mb-1">
          {title}
        </h1>
        
        {/* Subtitle (optional) */}
        {subtitle && (
          <p className="text-msn-gray-500 dark:text-msn-gray-400 text-sm">
            {subtitle}
          </p>
        )}
      </div>
      
      {/* Content */}
      <div className="px-6 py-4">
        {children}
      </div>
      
      {/* Footer (optional) */}
      {footer && (
        <div className="px-6 py-4 bg-msn-gray-50 dark:bg-msn-gray-700/50 border-t border-msn-gray-200 dark:border-msn-gray-700 text-center text-sm text-msn-gray-500 dark:text-msn-gray-400">
          {footer}
        </div>
      )}
    </motion.div>
  );
};

export default AuthCard;
