// =================================================================
// ██████╗██╗  ██╗ █████╗ ████████╗███████╗██████╗  █████╗ 
// ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗
// ██║     ███████║███████║   ██║   █████╗  ██████╔╝███████║
// ██║     ██╔══██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║
// ╚██████╗██║  ██║██║  ██║   ██║   ███████╗██║  ██║██║  ██║
//  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
// GENERATED BY CLAUDE: ChatEra v1.0 – 2025-05-13
// =================================================================

/**
 * ChatEra Shared Library
 * 
 * This package contains common types, utilities, and validation logic
 * shared between the frontend and backend services of the ChatEra platform.
 * 
 * It ensures consistent type safety and behavior across all parts of the
 * application ecosystem while enabling cross-platform compatibility.
 */

// Export all types
export * from './types';

// Export all utilities
export * from './utils';

// Export validators
export * from './validators';
